const statesInIndia = [
  { label: "Bihar", value: "Bihar" },
  { label: "Uttar Pradesh", value: "Uttar_Pradesh" },
  { label: "Madhya Pradesh", value: "Madhya Pradesh" },
  { label: "Goa", value: "Goa" },
  { label: "Jharkhand", value: "Jharkhand" },
  { label: "Andhra Pradesh", value: "Andhra_Pradesh" },
  { label: "Arunachal Pradesh", value: "Arunachal_Pradesh" },
  { label: "West Bengal", value: "West_Bengal" },
  { label: "Chhattisgarh", value: "Chhattisgarh" },
  { label: "Gujarat", value: "Gujarat" },
  { label: "Haryana", value: "Haryana" },
  { label: "Himachal Pradesh", value: "Himachal_Pradesh" },
  { label: "Karnataka", value: "Karnataka" },
  { label: "Kerala", value: "Kerala" },
  { label: "Maharashtra", value: "Maharashtra" },
  { label: "Manipur", value: "Manipur" },
  { label: "Meghalaya", value: "Meghalaya" },
  { label: "Mizoram", value: "Mizoram" },
  { label: "Nagaland", value: "Nagaland" },
  { label: "Odisha", value: "Odisha" },
  { label: "Punjab", value: "Punjab" },
  { label: "Rajasthan", value: "Rajasthan" },
  { label: "Sikkim", value: "Sikkim" },
  { label: "Tamil Nadu", value: "Tamil_Nadu" },
  { label: "Telangana", value: "Telangana" },
  { label: "Tripura", value: "Tripura" },
  { label: "Uttarakhand", value: "Uttarakhand" },
  { label: "Assam", value: "Assam" },
];

export default statesInIndia;
